name: Build driver solution

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '[17.0,18.0)'
          msbuild-architecture: x64
          
      - name: Download WDK
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2196230" -OutFile "wdksetup.exe"
          Start-Process -FilePath "wdksetup.exe" -ArgumentList "/quiet" -Wait
          
      - name: Build solution
        run: msbuild AudioMirror.sln /p:WindowsTargetPlatformVersion=10.0.22000.0 /p:Configuration=Release /p:Platform=x64
